### ISSUE TITLE
Zero-pad dated quicksaves so they respect alphabetical order

### ISSUE THREAD

**Issue by charlesstaats** [linuxgurugamer/Magico13_Modlets#4]
If I understand correctly, the change should be as simple as replacing every `]` with `0]` in https://github.com/linuxgurugamer/Magico13_Modlets/blob/58badd6ef24f3647be504c7e789c39a57ee5fe0a/DatedQuickSaves/DatedQuickSaves.cs#L185

See https://github.com/magico13/Modlets/issues/6#issuecomment-616731606

Additional note: I think this is actually causing a bug in which, e.g. after you switch from D99 to D100 the *newest* quicksaves are garbage-collected instead of the *oldest* quicksaves. But I'm not sure of that. Relevant lines: 
https://github.com/linuxgurugamer/Magico13_Modlets/blob/58badd6ef24f3647be504c7e789c39a57ee5fe0a/DatedQuickSaves/DatedQuickSaves.cs#L157
https://github.com/linuxgurugamer/Magico13_Modlets/blob/58badd6ef24f3647be504c7e789c39a57ee5fe0a/DatedQuickSaves/DatedQuickSaves.cs#L107
I don't see how the list is sorted, but I could be missing something.

In any case, even if the bug is not valid, the feature request definitely is, since named saves are sorted lexicographically.

**Comment by linuxgurugamer** [comment]
Added, thanks for the info.
Please let me know if you still have the problem with the 99-100
